### PR TITLE
Fix installation error of libpam-chksshpwd

### PR DESCRIPTION
**Pull request by diogomsantos**
More info at:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=172787&p=1137479&hilit=chksshpwd#p1137220

### CODE REVIEW

**Comment by spl237** [comment]
Thanks for this - now I look at it, we actually don't need to create that directory at all any more, so I'll remove the line from the script.

**Comment by diogomsantos** [comment]
Ok do as you like, but fix it please, your latest package, like it is, is broken and requires manual intervention to get updated.

**Comment by spl237** [comment]
Give us a chance, it's the weekend and I don't have access to the repo to upload fixed packages! I'll get an update on the repo tomorrow if you can be patient until then...

**Comment by diogomsantos** [comment]
Sure, no problem, when you have time ;)

**Pull request closed without merging**
